- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 0
    - !type:OverallPlaytimeRequirement
      time: 0
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    # Harmony Change Start
    # id: SalvagePDA - Harmony change
    # ears: ClothingHeadsetCargo
    ears: ClothingHeadsetMining # Salvage Channel
    # Harmony Change End
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: SalvageSpecialistChameleonOutfit
  job: SalvageSpecialist
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesColorBlack

