- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleConspirator
  name: Conspirator Role
  components:
  - type: ConspiratorRole
  - type: MindRole
    antagPrototype: Conspirator
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-conspirator
